### PR TITLE
[WIP] Update to JupyterLab 3

### PR DESCRIPTION
**Pull request by jrbourbeau**
cc @ian-r-rose

### CODE REVIEW

**Review by ian-r-rose — APPROVED** [review]
LGTM

**Comment by ian-r-rose** [comment]
Have you checked whether the workspace import still works? That format has historically not been especially stable

**Comment by jrbourbeau** [comment]
Checking now https://mybinder.org/v2/gh/jrbourbeau/dask-examples/jlab-3

**Comment by jrbourbeau** [comment]
Hmm it looks like the workspace import isn't working anymore. Were there changes on the JupyterLab side, or are the stability issues related to something else? 

Screen Shot 2021-03-23 at 2 57 33 PM

**Comment by ian-r-rose** [comment]
Probably a change in the JupyterLab side. There really isn't any guarantee of of compatibility for these files from version to version, since their primary intent is to store your ephemeral session state. If you're willing to wait a day or two on this (and the tutorials) PR, I could look into it.

**Comment by jrbourbeau** [comment]
That'd be great whenever you get a chance -- though no rush. Upgrading to JupyterLab 3 is nice to have but not critical

**Comment by jrbourbeau** [comment]
Closing in favor of https://github.com/dask/dask-examples/pull/217

**Pull request closed without merging**
