### PR TITLE
Avoid backticks in links in text vectorization example

### PR DESCRIPTION
**Pull request by mrocklin**
Sphinx wasn't rendering these correctly

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I was just fixing those :) I'm happy to see that we made the exact same changes.

**Comment by mrocklin** [comment]
:)

**Comment by mrocklin** [comment]
I was going through the page because I was going to schedule a tweet about
it.  Any interest in trying that out?

**Comment by TomAugspurger** [comment]
Yep, will do. Schedule for tomorrow?

**Comment by mrocklin** [comment]
Sure!

**Pull request merged**
