### PR TITLE
Delete unused file

### PR DESCRIPTION
**Pull request by jsignell**
I am fairly confident that this file isn't actually being used. It would be good to trigger a dev build though, just in case.

### CODE REVIEW

**Comment by quasiben** [comment]
I don't think it's being used either.  @TomAugspurger i want to double check with you

**Comment by quasiben** [comment]
@jsignell this is your first contribution.  welcome!

**Comment by jsignell** [comment]
Yes my goal is to have only red contributions :)

**Comment by jrbourbeau** [comment]
Thanks @jsignell! 

> Yes my goal is to have only red contributions :)

+1

**Pull request merged**
