### PR TITLE
Update notebook header

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR highlights our existing header (with binder and GitHub links) using the sphinx `.. admonition` directive. 

Screen Shot 2019-09-04 at 9 10 24 PM

While we're thinking about this, we could also try:

- Further customizing the title of the blue box (I went with "Live Notebook", but am totally open to other suggestions)

- Using a different binder button that makes more sense if you don't know what binder is (e.g. something like [![badge](https://img.shields.io/badge/-launch%20live%20notebook-579ACA.svg?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFkAAABZCAMAAABi1XidAAAB8lBMVEX///9XmsrmZYH1olJXmsr1olJXmsrmZYH1olJXmsr1olJXmsrmZYH1olL1olJXmsr1olJXmsrmZYH1olL1olJXmsrmZYH1olJXmsr1olL1olJXmsrmZYH1olL1olJXmsrmZYH1olL1olL0nFf1olJXmsrmZYH1olJXmsq8dZb1olJXmsrmZYH1olJXmspXmspXmsr1olL1olJXmsrmZYH1olJXmsr1olL1olJXmsrmZYH1olL1olLeaIVXmsrmZYH1olL1olL1olJXmsrmZYH1olLna31Xmsr1olJXmsr1olJXmsrmZYH1olLqoVr1olJXmsr1olJXmsrmZYH1olL1olKkfaPobXvviGabgadXmsqThKuofKHmZ4Dobnr1olJXmsr1olJXmspXmsr1olJXmsrfZ4TuhWn1olL1olJXmsqBi7X1olJXmspZmslbmMhbmsdemsVfl8ZgmsNim8Jpk8F0m7R4m7F5nLB6jbh7jbiDirOEibOGnKaMhq+PnaCVg6qWg6qegKaff6WhnpKofKGtnomxeZy3noG6dZi+n3vCcpPDcpPGn3bLb4/Mb47UbIrVa4rYoGjdaIbeaIXhoWHmZYHobXvpcHjqdHXreHLroVrsfG/uhGnuh2bwj2Hxk17yl1vzmljzm1j0nlX1olL3AJXWAAAAbXRSTlMAEBAQHx8gICAuLjAwMDw9PUBAQEpQUFBXV1hgYGBkcHBwcXl8gICAgoiIkJCQlJicnJ2goKCmqK+wsLC4usDAwMjP0NDQ1NbW3Nzg4ODi5+3v8PDw8/T09PX29vb39/f5+fr7+/z8/Pz9/v7+zczCxgAABC5JREFUeAHN1ul3k0UUBvCb1CTVpmpaitAGSLSpSuKCLWpbTKNJFGlcSMAFF63iUmRccNG6gLbuxkXU66JAUef/9LSpmXnyLr3T5AO/rzl5zj137p136BISy44fKJXuGN/d19PUfYeO67Znqtf2KH33Id1psXoFdW30sPZ1sMvs2D060AHqws4FHeJojLZqnw53cmfvg+XR8mC0OEjuxrXEkX5ydeVJLVIlV0e10PXk5k7dYeHu7Cj1j+49uKg7uLU61tGLw1lq27ugQYlclHC4bgv7VQ+TAyj5Zc/UjsPvs1sd5cWryWObtvWT2EPa4rtnWW3JkpjggEpbOsPr7F7EyNewtpBIslA7p43HCsnwooXTEc3UmPmCNn5lrqTJxy6nRmcavGZVt/3Da2pD5NHvsOHJCrdc1G2r3DITpU7yic7w/7Rxnjc0kt5GC4djiv2Sz3Fb2iEZg41/ddsFDoyuYrIkmFehz0HR2thPgQqMyQYb2OtB0WxsZ3BeG3+wpRb1vzl2UYBog8FfGhttFKjtAclnZYrRo9ryG9uG/FZQU4AEg8ZE9LjGMzTmqKXPLnlWVnIlQQTvxJf8ip7VgjZjyVPrjw1te5otM7RmP7xm+sK2Gv9I8Gi++BRbEkR9EBw8zRUcKxwp73xkaLiqQb+kGduJTNHG72zcW9LoJgqQxpP3/Tj//c3yB0tqzaml05/+orHLksVO+95kX7/7qgJvnjlrfr2Ggsyx0eoy9uPzN5SPd86aXggOsEKW2Prz7du3VID3/tzs/sSRs2w7ovVHKtjrX2pd7ZMlTxAYfBAL9jiDwfLkq55Tm7ifhMlTGPyCAs7RFRhn47JnlcB9RM5T97ASuZXIcVNuUDIndpDbdsfrqsOppeXl5Y+XVKdjFCTh+zGaVuj0d9zy05PPK3QzBamxdwtTCrzyg/2Rvf2EstUjordGwa/kx9mSJLr8mLLtCW8HHGJc2R5hS219IiF6PnTusOqcMl57gm0Z8kanKMAQg0qSyuZfn7zItsbGyO9QlnxY0eCuD1XL2ys/MsrQhltE7Ug0uFOzufJFE2PxBo/YAx8XPPdDwWN0MrDRYIZF0mSMKCNHgaIVFoBbNoLJ7tEQDKxGF0kcLQimojCZopv0OkNOyWCCg9XMVAi7ARJzQdM2QUh0gmBozjc3Skg6dSBRqDGYSUOu66Zg+I2fNZs/M3/f/Grl/XnyF1Gw3VKCez0PN5IUfFLqvgUN4C0qNqYs5YhPL+aVZYDE4IpUk57oSFnJm4FyCqqOE0jhY2SMyLFoo56zyo6becOS5UVDdj7Vih0zp+tcMhwRpBeLyqtIjlJKAIZSbI8SGSF3k0pA3mR5tHuwPFoa7N7reoq2bqCsAk1HqCu5uvI1n6JuRXI+S1Mco54YmYTwcn6Aeic+kssXi8XpXC4V3t7/ADuTNKaQJdScAAAAAElFTkSuQmCC)](https://)) 

xref #94

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Hmm I'm able to reproduce the slow behavior when running `json-data-on-the-web.ipynb` locally. It looks like there are Dask bag `from_delayed` calls that aren't failing, but are taking a few minutes each to complete. Not sure what the root of the problem is yet. The notebook pulls data from https://archive.analytics.mybinder.org/, but just manually downloading a file and loading with pandas works fine (takes around a second)

**Comment by jrbourbeau** [comment]
Running the corresponding notebook on the example's binder also works fine, so it's not an issue with https://archive.analytics.mybinder.org/

**Comment by jrbourbeau** [comment]
Downgrading the `fsspec` version locally from the current release (`0.4.4`) to what's in the already built image on binder (`0.4.1`) fixed the problem for me locally

**Comment by TomAugspurger** [comment]
Hmm, which snippet is failing? (cc @martindurant)

**Comment by martindurant** [comment]
OK, so in `readuntil()` (used in readline/iter), the code is extending the current block out to a full block, which is then always a line beyond the end of the current block, so we are requesting a full 5MB for every line. The following code greatly improves this for the case that the data is less than a blocksize (this case):
```diff
--- a/fsspec/implementations/http.py
+++ b/fsspec/implementations/http.py
@@ -234,11 +234,12 @@ class HTTPFile(AbstractBufferedFile):
         This is only called when position is still at zero,
         and read() is called without a byte-count.
         """
-        r = self.session.get(self.url, **self.kwargs)
-        r.raise_for_status()
-        out = r.content
-        self.cache = AllBytes(out)
-        self.size = len(out)
+        if not isinstance(self.cache, AllBytes):
+            r = self.session.get(self.url, **self.kwargs)
+            r.raise_for_status()
+            out = r.content
+            self.cache = AllBytes(out)
+            self.size = len(out)
```

I am open to suggestions for something more general. I am thinking that the current BytesCache should just be simplified to be read-ahead only, instead of the complex logic that has caused so many problems and situations like this.

**Comment by TomAugspurger** [comment]
Without fully understanding the situation, +1 to simplifying BytesCache :)

**Comment by martindurant** [comment]
@TomAugspurger , can you please have a careful look at the code in https://github.com/intake/filesystem_spec/pull/128 ?

**Comment by quasiben** [comment]
@TomAugspurger and I were chatting and we came to the conclusion that perhaps ignoring the CI failure for now would be ok.  The improvement is really great -- downgrading seems like the wrong course given other recent improvements to `fsspec`.  Thoughts?

Note: @martindurant added a PR with the suggested code changes: https://github.com/intake/filesystem_spec/pull/128

**Comment by jrbourbeau** [comment]
I'm not sure we can ignore the CI failure since that's where the sphinx docs are built / deployed. Is there a way to tell `nbsphinx` to skip a specific notebook? 

I don't have a full understanding of the changes in https://github.com/intake/filesystem_spec/pull/128, but FWIW I can confirm it fixes the problem we're seeing in `json-data-on-the-web.ipynb`

**Comment by quasiben** [comment]
You can ignore errors https://nbsphinx.readthedocs.io/en/0.2.7/allow-errors.html but that might not be want you want.

**Comment by mrocklin** [comment]
We would like to have the rendered notebook.  And we might not want to
share the example at all if it doesn't work.

**Comment by martindurant** [comment]
@jrbourbeau , @quasiben , @mrocklin all very welcome to look at  intake/filesystem_spec#128 - I have not yet decided if the simpler caching should be the default (it makes no difference for this HTTP case, because the data is less than one blocksize big)

**Comment by martindurant** [comment]
If you are installing fsspec from master, then this can be closed.

**Comment by quasiben** [comment]
All checks passed!  Hooray.  @jrbourbeau should we merge ?

**Comment by quasiben** [comment]
If the merge happens we should open up another issue to replace the dev fsspec with the released version

**Comment by jrbourbeau** [comment]
> we should open up another issue to replace the dev fsspec with the released version

Great idea : ) xref #96

**Comment by jrbourbeau** [comment]
Also, thanks for fixing upstream @martindurant!

**Pull request merged**
