### PR TITLE
Allow linking to sections on index

### PR DESCRIPTION
**Pull request by stsievert**
**What does this PR implement?**
In Dask-ML, I want to link to the section titled with "Machine learning". This PR allows that, so links like `http://examples.dask.org/#machine-learning` will resolve to the correct section.

**Reference issues/PRs**
This motivation is with https://github.com/dask/dask-ml/pull/642 (which depends on this PR).

### CODE REVIEW

**Comment by stsievert** [comment]
This does have slightly different styling:

Screen Shot 2020-04-12 at 11 08 28 AM

**Comment by stsievert** [comment]
The CI failure looks unrelated; the error is thrown in one of the Scikit-image notebooks cells on writing an image. Here's the traceback:

<details>

``` 
------------------
import os
from skimage import data, io
output_filename = os.path.join('temp', 'astronaut.png')
io.imsave(output_filename, data.astronaut())
------------------
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d9b70a345968> in <module>
      3
      4 output_filename = os.path.join('temp', 'astronaut.png')
----> 5 io.imsave(output_filename, data.astronaut())
~/miniconda/envs/test/lib/python3.7/site-packages/skimage/data/__init__.py in astronaut()
    129     """
    130
--> 131     return _load("astronaut.png")
    132
    133
~/miniconda/envs/test/lib/python3.7/site-packages/skimage/data/__init__.py in _load(f, as_gray)
     94     # we lazy import it here
     95     from ..io import imread
---> 96     return imread(_os.path.join(data_dir, f), plugin='pil', as_gray=as_gray)
     97
     98
~/miniconda/envs/test/lib/python3.7/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, **plugin_args)
     46
     47     with file_or_url_context(fname) as fname:
---> 48         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     49
     50     if not hasattr(img, 'ndim'):
~/miniconda/envs/test/lib/python3.7/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209
--> 210     return func(*args, **kwargs)
    211
    212
~/miniconda/envs/test/lib/python3.7/site-packages/skimage/io/_plugins/pil_plugin.py in imread(fname, dtype, img_num, **kwargs)
     34         with open(fname, 'rb') as f:
     35             im = Image.open(f)
---> 36             return pil_to_ndarray(im, dtype=dtype, img_num=img_num)
     37     else:
     38         im = Image.open(fname)
~/miniconda/envs/test/lib/python3.7/site-packages/skimage/io/_plugins/pil_plugin.py in pil_to_ndarray(image, dtype, img_num)
     64     while 1:
     65         try:
---> 66             image.seek(i)
     67         except EOFError:
     68             break
~/miniconda/envs/test/lib/python3.7/site-packages/PIL/PngImagePlugin.py in seek(self, frame)
    746         for f in range(self.__frame + 1, frame + 1):
    747             try:
--> 748                 self._seek(f)
    749             except EOFError:
    750                 self.seek(last_frame)
~/miniconda/envs/test/lib/python3.7/site-packages/PIL/PngImagePlugin.py in _seek(self, frame, rewind)
    789
    790             try:
--> 791                 cid, pos, length = self.png.read()
    792             except (struct.error, SyntaxError):
    793                 break
AttributeError: 'NoneType' object has no attribute 'read'
```

</details>

**Comment by TomAugspurger** [comment]
Looks like some issue upstream in pillow: https://github.com/python-pillow/Pillow/issues/4509

I've pushed a commit pinning to 7.0.0 for now.

**Comment by TomAugspurger** [comment]
Thanks!

**Pull request merged**
