### PR TITLE
Add torch prediction example

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/dask/dask-examples/issues/111.

Because pytorch / torchvision are so large, I don't think it's feasible to include them in the base image. 

I've opted to exclude this notebook from execution and have instead included the rendered output in the source.

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks for doing this Tom! 

I wonder if we can do everything in a single compute call. Currently it looks like we use dask.delayed to construct batches, and then we make a function that calls dask.compute on a *single* batch, and then uses torch.  Then we map that function across all of the batches.  This seems to mix things in a way that, while it works here, I suspect might trip up users in the future.

Instead, I wonder if we might do something like this:

```python
images = [load(fn) for fn in ...]
batches = [...]
model = dask.delayed(finetune_model)()

@dask.delayed
def predict(batch, model):
    with torch.no_grad():
        out = model(batch)
        _, predicted = torch.max(out, 1)
        predicted = predicted.numpy()
    return predicted

predictions = [predict(batch, model) for batch in batches]

predictions = dask.compute(*predictions)
```

**Comment by TomAugspurger** [comment]
Yeah, that should be doable, I'll just need to restructure the narrative a
bit. It did feel strange mixing delayed and Future.

**Comment by TomAugspurger** [comment]
Implemented essentially that, aside from `model = dask.delayed(finetune_model)()`. PyTorch didn't like the training ending up on a Worker (something about a subprocess daemon).

So I train the model on the client, and use

```
delayed_model = dask.delayed(model)
```

as the object passed to the delayed `predict`.

**Comment by mrocklin** [comment]
Some other small comments

- We might want to remove the `def batch` function
- We shouldn't need the `dask.compute` call in the `predict` function
-  Typo with `neurel`
-  "For a larger dataset, you would want to build up a dask.Array using dask.Array.from_delayed, or write the data to a shared filesystem or cloud storage."  I think that array is orthogonal here.  If it was a larger dataset then they might want to use persist or, as you suggest write things.  Array itself should be no different than delayed though when it comes to handling large outputs.

**Comment by TomAugspurger** [comment]
> For a larger dataset, you would want to build up a dask.Array

That was unclear. I meant you might want to build up an array from the `predictions`, rather than `dask.compute(...)`. No change to any previous step.

**Comment by TomAugspurger** [comment]
Planning to merge this later today.

**Comment by mrocklin** [comment]
Two comments:

1. In other cases where we have depended on large packages that we didn't want to include in the binder environment we call `!pip install foo` on the first cell.  Would it makes sense to do this here or is PyTorch too big?
2.  We'll need to be a little bit careful with section headers.  The section headers in the notebook end up populating the table of contents.  In particular, we should have a top-level / h1 section header at the top of the document with the title of the document like `# Scale Pytorch Predictions` or something similar that matches the form of the other titles (see the TOC on https://examples.dask.org).  We should use `h2` and other headers appropriately so that we get the right nesting.

**Comment by mrocklin** [comment]
The content here seems great to me

**Comment by TomAugspurger** [comment]
Fixed the header, thanks.

Will try running the example. The previous build (not running) took 21 minutes.

**Comment by TomAugspurger** [comment]
I'm not sure why the `torchvision` import is failing.

**Comment by TomAugspurger** [comment]
Status update: when I changed to `!pip install pytorch torchvision` (or `!conda`) the CI was failing in an `import torchvision`. I wasn't able to figure out why.

If others are OK with it, I'd prefer to just merge this as is (with the output included, and the execution skipped).

**Comment by mrocklin** [comment]
Sounds good to me

**Pull request merged**
