### PR TITLE
doctr

### PR DESCRIPTION
**Pull request by TomAugspurger**
Waiting on #41

### CODE REVIEW

**Comment by mrocklin** [comment]
Rebased and force pushed

**Comment by mrocklin** [comment]
Looks like the build worked well but some final deploy steps failed?

**Comment by TomAugspurger** [comment]
I had the wrong directory for the built docs.

I didn't change anything that would have affected the runtime of the notebooks though. I suppose it's possible the extra verbose output kept travis from timing out the build.

**Comment by TomAugspurger** [comment]
Passing now.

We may want to reduce the verbosity a bit and see if things still pass, but I assume we'll have followup PRs to tweak some things after this is live.

**Comment by TomAugspurger** [comment]
Build at https://travis-ci.org/dask/dask-examples/builds/429316672

Once that finishes, it should automatically create a `gh_pages` branch.

Then we can add `examples.dask.org` as the domain through the github settings.

**Comment by TomAugspurger** [comment]
Here's the built example.

**Pull request merged**
