### PR TITLE
Allow for arbitrary base URL in Dashboard link

### LINKED ISSUE #128: Dashboard link broken on some binder deployments.
See <https://discourse.jupyter.org/t/gesis-hub-blocks-dask-dashboard/3019>.

With
<https://github.com/dask/dask-examples/blob/c14b7dc809c17066224cb5b8353e78c9aebe9ccc/binder/start#L4> 
assuming that the full URL always is along the lines of `https://binder.something.example.com/user/${JUPYTERHUB_USER}/proxy/8787` which is not necessarily true.

### PR DESCRIPTION
**Pull request by willirath**
Fixes #128.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
I think https://github.com/dask/dask-examples/pull/130 is fixing the CI issues.

**Comment by quasiben** [comment]
@willirath , I think that for mybinder `JUPYTERHUB_BASE_URL` is set to `/`.  My URL knowledge is not up to par -- will the extra slash mess up the proxying ?

> //user/dask-dask-tutorial-a9xurrci/proxy/8787

**Comment by willirath** [comment]
@quasiben I've re-checked and

- Found that I forgot to also adapt the dask config. (I only changed the dask labview default URL intially.)

- Adapted the startup script to avoid the leading slash. On the GKE and OVH binder hubs, `${JUPYTERHUB_BASE_URL}="/"` and on the Gesis hub, `${JUPYTERHUB_BASE_URL}="/binder/jupyter/".

It's now working on all three (GKE, OVH, and Gesis) BinderHubs.

**Comment by quasiben** [comment]
Thanks @willirath for confirming the solution on other binderhubs.  Is this critical to get in soon or can we wait for #130 to fix CI ?

**Comment by willirath** [comment]
No objections to waiting till CI is fixed.


Am 14. Januar 2020 04:19:22 schrieb Benjamin Zaitlen <notifications@github.com>:

**Pull request merged**
