### PR TITLE
Update dependency versions in binder environment

### PR DESCRIPTION
**Pull request by GenevieveBuckley**
The dependency versions in the binder environment file have fallen reasonably out of date. This pull request brings it up to date.

Version upgrades for pinned dependencies:
```
bokeh=0.13        --> bokeh=1.0.4
dask=0.20         --> dask=1.1.4
dask-ml=0.10.0    --> dask-ml=0.12.0
distributed=1.24  -->  distributed=1.26
```

Closes https://github.com/dask/dask-examples/issues/62

### CODE REVIEW

**Comment by mrocklin** [comment]
It looks like there was another small issue with groupby aggregations.  I've resolved this in master and things now pass here.  I'll probably push out another micro-release at the end of the week and then we can merge this in.

**Comment by jakirkham** [comment]
Thanks for helping with this, Genevieve! :)

**Comment by jakirkham** [comment]
So Dask 1.1.4 has landed. Should we update to that? Anything else needed here?

**Comment by GenevieveBuckley** [comment]
> So Dask 1.1.4 has landed. Should we update to that? Anything else needed here?

Dask version updated, thanks! Tests pass.

Two final questions:

1. Should we use conda install wherever possible? As far as I can tell, these packages are all available on conda-forge (at least they are now, not sure about when the environment file was put together):
* `dask_xgboost`
* `seaborn`
* `graphviz`

2. And on that last point, I think we should probably replace this with a conda install of `python-graphviz` from conda-forge, to match with the recommendation [given in the dask docs](http://docs.dask.org/en/latest/graphviz.html). Do other people agree?

**Comment by mrocklin** [comment]
Conda's default `graphviz` package is sometimes broken, which I think is probably why we were using pip and the system library here.  I'll give it a shot and see what happens.

Also, a binder link for this PR is here: https://mybinder.org/v2/gh/GenevieveBuckley/dask-examples/update-binder-env?urlpath=lab

**Comment by mrocklin** [comment]
Looks good.  Merging this in.  Thanks for sticking with this @GenevieveBuckley !

**Pull request merged**
