### PR TITLE
Upgrade environment to Dask 2.2

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by mrocklin** [comment]
Everything seems to work with the current environment except for the HTTP issue with the json-on-the-web example.  (I think that @martindurant is taking a look.)  In the meantime I've also tried updating/pinning a few other libraries to see if we can increase them at the same time.

**Comment by martindurant** [comment]
https://github.com/intake/filesystem_spec/pull/82

**Comment by mrocklin** [comment]
We're green.  Thanks @martindurant for the speedy work

**Comment by martindurant** [comment]
Is this waiting for Dask's release?

**Comment by mrocklin** [comment]
Yes.  Then I'll clean up the binder environment and merge this in.

**Pull request merged**
