### PR TITLE
Add user survey results.

### PR DESCRIPTION
**Pull request by TomAugspurger**
When compressed, the dataset is smaller than the notebook and our
image files, so I've included it in the repo.

Should we include the analysis I did for the blog post? Or should we leave it relatively spare? My preference is for including the blog post analysis.

### CODE REVIEW

**Comment by mrocklin** [comment]
Maybe rename `results.csv.gz` to `dask-user-survey-2019.csv.gz`?

**Comment by TomAugspurger** [comment]
Will do.

Want to publish this on Monday so we don't have two posts on the same day?

**Comment by mrocklin** [comment]
Sure.

**Comment by mrocklin** [comment]
I also haven't publicized the release post yet if you wanted to switch around the order.

**Comment by TomAugspurger** [comment]
I think release first makes the most sense because it's already out.

**Comment by TomAugspurger** [comment]
This and the blog post https://github.com/dask/dask-blog/pull/45 should be good to go. Merging later today.

We'll merge this a bit before the blog post, since the post references this notebook (on master).

**Pull request merged**
