### PR TITLE
Bump dask to 2.8

### PR DESCRIPTION
**Pull request by mrocklin**
And bokeh to 1.4

### CODE REVIEW

**Comment by mrocklin** [comment]
@TomAugspurger does the scikit-learn error here mean anything to you?

**Comment by TomAugspurger** [comment]
Looks like the output shape of the CountVectorizer depends on the actual words present in the CV split. I'm surprised this hasn't failed before.

I'll push a fix here shortly.

**Comment by mrocklin** [comment]
Thanks @TomAugspurger !

Oddly, it appears that there is another, possibly related failure

```python-traceback
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/nbsphinx.py", line 860, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/nbsphinx.py", line 767, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
import joblib
with joblib.parallel_backend('dask'):
    grid_search.fit(data.data, data.target)
------------------
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-e1347a4add69> in <module>
      2 
      3 with joblib.parallel_backend('dask'):
----> 4     grid_search.fit(data.data, data.target)
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    686                 return results
    687 
--> 688             self._run_search(evaluate_candidates)
    689 
    690         # For multi-metric evaluation, store the best_index_, best_params_ and
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_search.py in _run_search(self, evaluate_candidates)
   1147     def _run_search(self, evaluate_candidates):
   1148         """Search all candidates in param_grid"""
-> 1149         evaluate_candidates(ParameterGrid(self.param_grid))
   1150 
   1151 
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_search.py in evaluate_candidates(candidate_params)
    665                                for parameters, (train, test)
    666                                in product(candidate_params,
--> 667                                           cv.split(X, y, groups)))
    668 
    669                 if len(out) < 1:
~/miniconda/envs/test/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1014 
   1015             with self._backend.retrieval_context():
-> 1016                 self.retrieve()
   1017             # Make sure that we get a last message telling us we are done
   1018             elapsed_time = time.time() - self._start_time
~/miniconda/envs/test/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    908                     self._output.extend(job.get(timeout=self.timeout))
    909                 else:
--> 910                     self._output.extend(job.get())
    911 
    912             except BaseException as exception:
~/miniconda/envs/test/lib/python3.7/site-packages/joblib/_dask.py in get()
    268 
    269         def get():
--> 270             return ref().result()
    271 
    272         future.get = get  # monkey patch to achieve AsyncResult API
~/miniconda/envs/test/lib/python3.7/site-packages/distributed/client.py in result(self, timeout)
    220         if self.status == "error":
    221             typ, exc, tb = result
--> 222             raise exc.with_traceback(tb)
    223         elif self.status == "cancelled":
    224             raise result
~/miniconda/envs/test/lib/python3.7/site-packages/joblib/_dask.py in __call__(self, *data)
    104                 kwargs = {k: v(data) if isinstance(v, itemgetter) else v
    105                           for (k, v) in kwargs.items()}
--> 106                 results.append(func(*args, **kwargs))
    107         return results
    108 
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, return_estimator, error_score)
    554         fit_time = time.time() - start_time
    555         # _score will return dict if is_multimetric is True
--> 556         test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
    557         score_time = time.time() - start_time - fit_time
    558         if return_train_score:
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _score(estimator, X_test, y_test, scorer, is_multimetric)
    597     """
    598     if is_multimetric:
--> 599         return _multimetric_score(estimator, X_test, y_test, scorer)
    600     else:
    601         if y_test is None:
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in _multimetric_score(estimator, X_test, y_test, scorers)
    627             score = scorer(estimator, X_test)
    628         else:
--> 629             score = scorer(estimator, X_test, y_test)
    630 
    631         if hasattr(score, 'item'):
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/metrics/scorer.py in _passthrough_scorer(estimator, *args, **kwargs)
    238 def _passthrough_scorer(estimator, *args, **kwargs):
    239     """Function that wraps estimator.score"""
--> 240     return estimator.score(*args, **kwargs)
    241 
    242 
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/utils/metaestimators.py in <lambda>(*args, **kwargs)
    114 
    115         # lambda, but not partial, allows help() to work with update_wrapper
--> 116         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
    117         # update the docstring of the returned function
    118         update_wrapper(out, self.fn)
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/pipeline.py in score(self, X, y, sample_weight)
    600         if sample_weight is not None:
    601             score_params['sample_weight'] = sample_weight
--> 602         return self.steps[-1][-1].score(Xt, y, **score_params)
    603 
    604     @property
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/base.py in score(self, X, y, sample_weight)
    355         """
    356         from .metrics import accuracy_score
--> 357         return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
    358 
    359 
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/linear_model/base.py in predict(self, X)
    287             Predicted class label per sample.
    288         """
--> 289         scores = self.decision_function(X)
    290         if len(scores.shape) == 1:
    291             indices = (scores > 0).astype(np.int)
~/miniconda/envs/test/lib/python3.7/site-packages/sklearn/linear_model/base.py in decision_function(self, X)
    265         X = check_array(X, accept_sparse='csr')
    266 
--> 267         n_features = self.coef_.shape[1]
    268         if X.shape[1] != n_features:
    269             raise ValueError("X has %d features per sample; expecting %d"
IndexError: tuple index out of range
IndexError: tuple index out of range

```

**Comment by TomAugspurger** [comment]
Taking a look.

**Comment by TomAugspurger** [comment]
I'm pretty stumped by this right now. Will have to revisit it later.

**Comment by mrocklin** [comment]
No worries.  Thanks for taking a look.

**Comment by TomAugspurger** [comment]
I'm not sure, but I think it's potentially a thread-safety issue in either joblib or one of the estimators (SGDClassifier or GridSearchCV, most likely). Haven't had time to investigate further, but https://github.com/dask/dask-examples/pull/120/commits/50d8cacb97c03388ca37bab61bc6c26e97ff108d removes `processes=False` to get CI passing here.

**Comment by TomAugspurger** [comment]
Seems to be passing now. Will keep an eye on the CI to see if it reappears.

**Comment by jrbourbeau** [comment]
Thanks @TomAugspurger!

**Pull request merged**
